[tool.poetry]
name = "sentiment-analysis"
version = "0.1.0"
description = ""
authors = ["BartoszW <bartoszwilkowski3@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
matplotlib = "^3.10.0"
nltk = "^3.9.1"
notebook = "^7.3.2"
numpy = ">=1.22,<1.24"
pandas = "^2.2.3"
scikit-learn = "^1.6.0"
seaborn = "^0.13.2"
spacy = "^3.8.3"
tensorflow = "2.10.0"
tensorflow-io-gcs-filesystem = "^0.31.0"
textattack = "^0.3.10"
transformers = "^4.47.1"
ipykernel = "^6.29.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
